import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ChangeEvent } from "react";
import LangSwitcher from "@/components/LangSwitcher";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  preload: true,
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: "en" | "np" }>;
}>) {
  const handleChange = (e: ChangeEvent<HTMLSelectElement>) => {
    redirect(`/${e.target.value}`);
  };
  return (
    <html lang={(await params).locale}>
      <body
        className={`${inter.variable} ${montserrat.variable} font-inter antialiased`}
      >
        <header className="bg-red-300 h-14 row-start-3 flex gap-6 flex-wrap items-center justify-center">
          <Link href={"/"}>Home</Link> Header
          <LangSwitcher />
        </header>
        <main>{children}</main>
        <footer className="bg-yellow-400 row-start-3 flex gap-6 flex-wrap h-32 items-center justify-center">
          Footer
        </footer>{" "}
      </body>
    </html>
  );
}
